# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonk < Formula
  desc "Yells 'ow!' when you bonk the laptop. Uses Apple Silicon accelerometer."
  homepage "https://github.com/notuselessdev/bonk"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/notuselessdev/bonk/releases/download/v0.1.0/bonk_0.1.0_darwin_arm64.tar.gz"
    sha256 "58c9ffc626f07d762a7c343272a05b1643143c14bb0a219b0da8abd3911d7238"

    define_method(:install) do
      bin.install "bonk"
    end
  end

  def caveats
    <<~EOS
      bonk requires sudo to access the accelerometer:
        sudo bonk
    EOS
  end

  test do
    system "#{bin}/bonk", "--version"
  end
end
